#!C:\Users\ANTECH\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.8\Python.exe
print("Content-type:text/html\r\n\r\n")
print('<!DOCTYPE html>')
print('<html>')
print('<head>')
print('	<title>1-Search</title>')
print('<link rel="stylesheet" type="text/css" href="css/css.css">')
print('<script type="text/javascript" src="js/js.js">')
print('</script>')
print('</head>')
print('<body>')
print('<center>')
print('<h1>1-Search</h1>')
print('<form action="index.py" onclick="showhide()">')
print('	<input type="text" name="txt_search" id="txt_search">')
print('	<input type="submit" name="btn_search" id="btn_search" value="Search">')
print('</form>')
print('<br>')
print('<hr>')
print('<br>')
print('<div class="tab" id="main_tab">')
print('	<button class="tablinks" onclick="openCity(event, 'Google')"> <img src="assets/google_icon.png" height="24px" width="24px"> Google</button>')
print('	<button class="tablinks" onclick="openCity(event, 'Yahoo')"> <img src="assets/yahoo_icon.png" height="24px" width="24px"> Yahoo</button>')
print('	<button class="tablinks" onclick="openCity(event, 'Bing')"> <img src="assets/bing_icon.png" height="24px" width="24px"> Bing</button>')
print('</div>')
print('<div id="Google"  class="tabcontent">')
print('<h3>Google</h3>')
print('<p>Google Data List including their data and  url will be dsiplayed here in a list format.</p>')
print('</div>')
print('<div id="Yahoo" class="tabcontent">')
print('<h3>Yahoo</h3>')
print('<p>Yahoo Data List including their data and  url will be dsiplayed here in a list format.</p>')
print('</div>')
print('<div id="Bing" class="tabcontent">')
print('<h3>Bing</h3>')
print('<p>Bing Data List including their data and  url will be dsiplayed here in a list format.</p>')
print('</div>')
print('</center>')
print('</body>')
print('</html>')